name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CI_EXECUTION_ID: ${{ github.sha }}-${{ github.run_attempt > 1 && github.workflow_sha || '' }}
  NX_CI_EXECUTION_ENV: One

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after e2e-ci

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm i --legacy-peer-deps

      - run: |
          echo "NX_BASE: $NX_BASE"
          echo "NX_HEAD: $NX_HEAD"
          echo "BASE_SHA: $BASE_SHA"
          echo "HEAD_SHA: $HEAD_SHA"
          echo "${{ github.event.pull_request.base.ref }}"
          echo "${{ github.base_ref }}"

      - uses: nrwl/nx-set-shas@v4

      - run: |
          echo "NX_BASE: $NX_BASE"
          echo "NX_HEAD: $NX_HEAD"
          echo "BASE_SHA: $BASE_SHA"
          echo "HEAD_SHA: $HEAD_SHA"
          echo "${{ github.event.pull_request.base.ref }}"
          echo "${{ github.base_ref }}"

      # - run: npx nx affected -t lint test build e2e-ci
      # - run: npx nx affected -t lint test build
